# -*- coding: utf-8 -*-
"""email_automation_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s7C_mnGVdHpwup8BALBKzCN1LfKwUwrw
"""



import smtplib, ssl
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import pandas as pd

df = pd.read_csv('email_list.csv') #insert list of emails

print(df)

#configuration
smtp_server = "smtp.gmail.com" #for gmail
port = 465
sender_email = "your_email3@gmail.com" #your email
password = "" #for any password

#send
context = ssl.create_default_context()


with smtplib.SMTP_SSL(smtp_server, port, context=context) as server:
  server.login(sender_email, password)
  for index, row in df.iterrows():
    receiver_email = row['email_id']
    #message creation
    message = MIMEMultipart()
    message["Subject"] = "Python reading from Excel automation test"
    message["From"] = sender_email
    message["To"] = receiver_email

    body = """
    Hello.
    This is just a test to check if this python program is working.

    """

    message.attach(MIMEText(body, "plain"))


    server.sendmail(sender_email, receiver_email, message.as_string())

print("email sent")

